# -*- coding: utf-8 -*-
"""C-114.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m6kX5BoMt70MehlP0O6bkx3H_4r1oxo4
"""

from google.colab import files
files=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv('data.csv')
gre_score=df['GRE Score'].tolist()
chances_of_admit=df['Chance of Admit '].tolist()
fig=px.scatter(x=gre_score,y=chances_of_admit)
fig.show()

import numpy as np
gre_score_array=np.array(gre_score)
chances_of_admit_array=np.array(chances_of_admit)
m,c=np.polyfit(gre_score_array,chances_of_admit_array,1)
y=[]
for x in gre_score_array:
  y_value=m*x+c
  y.append(y_value)
fig=px.scatter(x=gre_score_array,y=chances_of_admit_array)
fig.update_layout(shapes=[
    dict(type='line',
        y0=min(y),
        y1=max(y),
        x0=min(gre_score_array),
        x1=max(gre_score_array)),
])
fig.show()

x=600
y=m*x+c
print(f'Chances of admit of someone with GRE score {x} is {y}')